name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04  # <--- Ye sab se zaroori tabdeeli hai
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Stable version

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libbz2-dev libsqlite3-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 kivy

      - name: Build with Buildozer
        run: |
          yes | buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Zeeshan-VIP-APK
          path: bin/*.apk
          
